In [20]:
import pandas as pd
df = pd.read_csv("ecommerce_customer_data_custom_ratios.csv")
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
0,46251,2020-09-08 09:38:32,Electronics,12,3,740,Credit Card,37,0.0,Christine Hernandez,37,Male,0
1,46251,2022-03-05 12:56:35,Home,468,4,2739,PayPal,37,0.0,Christine Hernandez,37,Male,0
2,46251,2022-05-23 18:18:01,Home,288,2,3196,PayPal,37,0.0,Christine Hernandez,37,Male,0
3,46251,2020-11-12 13:13:29,Clothing,196,1,3509,PayPal,37,0.0,Christine Hernandez,37,Male,0
4,13593,2020-11-27 17:55:11,Home,449,1,3452,Credit Card,49,0.0,James Grant,49,Female,1

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  int64
 1   Purchase Date          250000 non-null  str
 2   Product Category       250000 non-null  str
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  str
 7   Customer Age           250000 non-null  int64
 8   Returns                202404 non-null  float64
 9   Customer Name          250000 non-null  str
 10  Age                    250000 non-null  int64
 11  Gender                 250000 non-null  str
 12  Churn                  250000 non-null  int64
dtypes: float64(1), int64(7), str(5)
memory usage: 24.8 MB

In [22]:
df.isnull().sum()

Customer ID                  0
Purchase Date                0
Product Category             0
Product Price                0
Quantity                     0
Total Purchase Amount        0
Payment Method               0
Customer Age                 0
Returns                  47596
Customer Name                0
Age                          0
Gender                       0
Churn                        0
dtype: int64

In [23]:
df.mean(numeric_only=True)

Customer ID              25004.036240
Product Price              254.659512
Quantity                     2.998896
Total Purchase Amount     2725.370732
Customer Age                43.940528
Returns                      0.497861
Age                         43.940528
Churn                        0.199496
dtype: float64

In [24]:
df.median(numeric_only=True)

Customer ID              25018.0
Product Price              255.0
Quantity                     3.0
Total Purchase Amount     2724.0
Customer Age                44.0
Returns                      0.0
Age                         44.0
Churn                        0.0
dtype: float64

In [25]:
df.mode().iloc[0]

Customer ID                            36437
Purchase Date            2022-05-08 12:58:55
Product Category                    Clothing
Product Price                          100.0
Quantity                                 1.0
Total Purchase Amount                 2786.0
Payment Method                   Credit Card
Customer Age                            58.0
Returns                                  0.0
Customer Name                  Michael Smith
Age                                     58.0
Gender                                Female
Churn                                    0.0
Name: 0, dtype: object

In [26]:
df.describe()

,Customer ID,Product Price,Quantity,Total Purchase Amount,Customer Age,Returns,Age,Churn
count,250000.00000,250000.000000,250000.000000,250000.000000,250000.000000,202404.000000,250000.000000,250000.000000
mean,25004.03624,254.659512,2.998896,2725.370732,43.940528,0.497861,43.940528,0.199496
std,14428.27959,141.568577,1.414694,1442.933565,15.350246,0.499997,15.350246,0.399622
min,1.00000,10.000000,1.000000,100.000000,18.000000,0.000000,18.000000,0.000000
25%,12497.75000,132.000000,2.000000,1477.000000,31.000000,0.000000,31.000000,0.000000
50%,25018.00000,255.000000,3.000000,2724.000000,44.000000,0.000000,44.000000,0.000000
75%,37506.00000,377.000000,4.000000,3974.000000,57.000000,1.000000,57.000000,0.000000
max,50000.00000,500.000000,5.000000,5350.000000,70.000000,1.000000,70.000000,1.000000

In [27]:
df.dtypes

Customer ID                int64
Purchase Date                str
Product Category             str
Product Price              int64
Quantity                   int64
Total Purchase Amount      int64
Payment Method               str
Customer Age               int64
Returns                  float64
Customer Name                str
Age                        int64
Gender                       str
Churn                      int64
dtype: object