In [3]:
import pandas as pd
df = pd.read_csv("superstoresales.csv", encoding="latin1")
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
0,1,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/6/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold N Roll Cart System,22.3680

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row_ID         9800 non-null   int64
 1   Order_ID       9800 non-null   str
 2   Order_Date     9800 non-null   str
 3   Ship_Date      9800 non-null   str
 4   Ship_Mode      9800 non-null   str
 5   Customer_ID    9800 non-null   str
 6   Customer_Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal_Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product_ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub_Category   9800 non-null   str
 16  Product_Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB

In [4]:
df.isnull().sum()

Row_ID            0
Order_ID          0
Order_Date        0
Ship_Date         0
Ship_Mode         0
Customer_ID       0
Customer_Name     0
Segment           0
Country           0
City              0
State             0
Postal_Code      11
Region            0
Product_ID        0
Category          0
Sub_Category      0
Product_Name      0
Sales             0
dtype: int64

In [5]:
df.describe()

            Row_ID   Postal_Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [6]:
df.dtypes

Row_ID             int64
Order_ID             str
Order_Date           str
Ship_Date            str
Ship_Mode            str
Customer_ID          str
Customer_Name        str
Segment              str
Country              str
City                 str
State                str
Postal_Code      float64
Region               str
Product_ID           str
Category             str
Sub_Category         str
Product_Name         str
Sales            float64
dtype: object

In [8]:
df.mean(numeric_only=True)

Row_ID          4900.500000
Postal_Code    55273.322403
Sales            230.769059
dtype: float64

In [9]:
df.median(numeric_only=True)

Row_ID          4900.50
Postal_Code    58103.00
Sales             54.49
dtype: float64

In [10]:
df.mode().iloc[0]

Row_ID                         1
Order_ID          CA-2018-100111
Order_Date              5/9/2017
Ship_Date             26/09/2018
Ship_Mode         Standard Class
Customer_ID             WB-21850
Customer_Name      William Brown
Segment                 Consumer
Country            United States
City               New York City
State                 California
Postal_Code              10035.0
Region                      West
Product_ID       OFF-PA-10001970
Category         Office Supplies
Sub_Category             Binders
Product_Name     Staple envelope
Sales                      12.96
Name: 0, dtype: object

In [11]:
df.duplicated().sum()

np.int64(0)

In [13]:
df["Sales"].sum()

np.float64(2261536.7827)

In [14]:
df["Sales"].mean()

np.float64(230.76905945918367)

In [15]:
df["Sales"].max()

np.float64(22638.48)

In [16]:
df["Sales"].min()

np.float64(0.444)

In [6]:
df["Order_ID"].nunique()

4922